Fix `expandAll` call so it works with a `Run` parameter.
Previously, due to the blanket catch of a `Throwable` here, the code was masking the fact that `TokenMacro.expandAll` was never invoked, failing like this:

```
Failed to evaluate macro ''
java.lang.ClassCastException: org.jenkinsci.plugins.workflow.job.WorkflowRun cannot be cast to hudson.model.AbstractBuild
```